name: remindify
description: A reminders app.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
  firebase_auth: ^4.1.1
  http: ^0.13.5
  google_sign_in: ^5.4.2
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.4
  get_it: ^7.2.0
  equatable: ^2.0.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  material_color_generator: ^1.1.0
  flutter_datetime_picker: ^1.5.1
  day_night_time_picker: ^1.1.3
  syncfusion_flutter_datepicker: ^20.3.52
  flutter_expanded_tile: ^0.3.6
  flutter_launcher_icons: ^0.10.0
  flutter_local_notifications: ^12.0.3
  timezone: ^0.9.0
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.5
  awesome_notifications: ^0.7.4+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

assets:


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon_512.png"
  min_sdk_android: 33 # android min sdk min:16, default 21


